version: '3.3'

services:

  streamer:
    image: dottgonzo/nginx-rtmp-docker
    environment:
      - RTMP_PASS=rtmptest
    volumes:
      - /tmp/ee:/data
    ports:
      - 4545:1935
      - 3880:80